# Generated by Django 4.2.20 on 2025-05-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_datacompleted_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id_beca', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Beca')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripción', models.TextField(verbose_name='Scholarship Descripción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beca', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
            },
        ),
    ]
