# Generated by Django 4.2.20 on 2025-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_becas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becas',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='becas',
            name='descripción',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
