# Generated by Django 4.2.20 on 2025-05-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_remove_becas_usuario_alter_becas_descripción'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la solicitud')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido completo')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('lugar_nac', models.CharField(max_length=255, verbose_name='Lugar de nacimiento')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula de identidad')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('est_civil', models.CharField(choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a')], max_length=20, verbose_name='Estado civil')),
                ('habitacion', models.CharField(max_length=255, verbose_name='Dirección de habitación')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de correo electrónico')),
                ('nivel_educ', models.CharField(choices=[('high_school', 'Bachillerato / Educación Media'), ('associate', 'Técnico superior universitario'), ('bachelor', 'Licenciatura / Ingeniería'), ('postgraduate', 'Postgrado')], max_length=50, verbose_name='Nivel de estudio actual')),
                ('inst_actual', models.CharField(max_length=255, verbose_name='Institución educativa actual')),
                ('programa', models.CharField(max_length=255, verbose_name='Carrera o programa')),
                ('semestre', models.CharField(max_length=20, verbose_name='Semestre o año')),
                ('indice_acad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Índice académico o promedio general')),
                ('necesidad', models.TextField(verbose_name='Necesidad de la beca')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado de la Solicitud')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solicitud', to='tasks.becas', verbose_name='Beca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solicitud', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
