# Generated by Django 4.2.20 on 2025-05-23 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Banco')),
                ('codigo_bancario', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Bancario')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstatusBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Estatus')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Estatus')),
            ],
            options={
                'verbose_name': 'Estatus de Beca',
                'verbose_name_plural': 'Estatus de Becas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='tasks.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plantel', models.CharField(max_length=255, verbose_name='Nombre del Plantel')),
                ('estado_plantel', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('Vargas', 'Vargas'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia'), ('Distrito Capital', 'Distrito Capital'), ('Dependencias Federales', 'Dependencias Federales')], max_length=50, verbose_name='Estado del Plantel')),
                ('municipio_plantel', models.CharField(max_length=100, verbose_name='Municipio del Plantel')),
                ('codigo_plantel', models.CharField(max_length=20, unique=True, verbose_name='Código del Plantel')),
                ('tipo_dependencia', models.CharField(choices=[('estadal', 'Estadal'), ('nacional', 'Nacional'), ('privada', 'Privada'), ('autonoma', 'Autónoma'), ('privada_mppe', 'Privada subvencionada por MPPE'), ('privada_oficial', 'Privada subvencionada por Oficial')], max_length=20, verbose_name='Tipo de Dependencia')),
                ('modalidad_principal', models.CharField(choices=[('jovenes', 'Jóvenes'), ('adultos', 'Adultos y adultas'), ('regular', 'Sistema Regular'), ('especial', 'Educación Especial')], max_length=20, verbose_name='Modalidad Principal')),
                ('estatus_plantel', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estatus del Plantel')),
            ],
            options={
                'verbose_name': 'Plantel',
                'verbose_name_plural': 'Planteles',
            },
        ),
        migrations.RenameField(
            model_name='becas',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='email',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='est_civil',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='indice_acad',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='inst_actual',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='lugar_nac',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='necesidad',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nivel_educ',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='status',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='telefono',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='boletin',
            field=models.ImageField(blank=True, null=True, upload_to='boletines/', verbose_name='Boletín (JPG)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='constancia_estudios',
            field=models.ImageField(blank=True, null=True, upload_to='constancias/', verbose_name='Constancia de Estudios (JPG)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_de_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.becas', verbose_name='Beca a solicitar'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cedula',
            field=models.ImageField(blank=True, null=True, upload_to='cedulas/', verbose_name='Cédula de Identidad (JPG)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Parroquia')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='tasks.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'municipio')},
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estatus_beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.estatusbeca', verbose_name='Estatus de la Beca'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.parroquia', verbose_name='Parroquia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.plantel', verbose_name='Plantel'),
        ),
    ]
