# Generated by Django 4.2.20 on 2025-06-09 17:29

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_banco_estado_estatusbeca_municipio_plantel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus_beca',
            field=models.ForeignKey(blank=True, default=tasks.models.get_default_estatus_beca, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tasks.estatusbeca', verbose_name='Estatus de la Beca'),
        ),
    ]
