# Generated by Django 4.2.20 on 2025-06-09 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_solicitud_estatus_beca'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
    ]
