# Generated by Django 4.2.20 on 2025-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_solicitud_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='constancia_numero_cuenta',
            field=models.ImageField(blank=True, null=True, upload_to='constancias/', verbose_name='Constancia de Número de Cuenta (JPG)'),
        ),
    ]
