# Generated by Django 4.2.20 on 2025-07-04 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_solicitud_constancia_numero_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre(s) completo(s)', max_length=100)),
                ('apellido_completo', models.CharField(help_text='Apellido(s) completo(s)', max_length=100)),
                ('edad', models.IntegerField(blank=True, help_text='Edad del usuario', null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Género del usuario', max_length=1, null=True)),
                ('cedula_identidad', models.CharField(help_text='Número de Cédula de Identidad', max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True)),
                ('numero_telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
