# Generated by Django 4.2.20 on 2025-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Género del usuario', max_length=1, null=True),
        ),
    ]
