# Generated by Django 4.2.20 on 2025-08-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_profile_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_analista_exterior',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es un analista exterior CDCE.'),
        ),
    ]
