# Generated by Django 4.2.20 on 2025-08-04 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_profile_is_analista_exterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_analista_exterior',
        ),
        migrations.CreateModel(
            name='AnalistaExterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analista_exterior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analista Exterior',
                'verbose_name_plural': 'Analistas Exteriores',
            },
        ),
    ]
