# Generated by Django 4.2.20 on 2025-08-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_profile_is_analista_exterior_analistaexterior'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalistaExterior',
        ),
    ]
