# Generated by Django 4.2.20 on 2025-08-04 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_analistaexterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaExteriorCDCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='Usuario de Django asociado al analista exterior.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Analista Exterior CDCE',
                'verbose_name_plural': 'Analistas Exteriores CDCE',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='is_analista_exterior',
            field=models.BooleanField(default=False, verbose_name='Es Analista Exterior'),
        ),
        migrations.DeleteModel(
            name='AnalistaExterior',
        ),
    ]
