# Generated by Django 4.2.20 on 2025-08-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_analistaexteriorcdce_profile_is_analista_exterior_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalistaExteriorCDCE',
        ),
    ]
