# Generated by Django 4.2.20 on 2025-08-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_delete_analistaexteriorcdce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_analista_exterior',
        ),
    ]
