# Generated by Django 4.2.20 on 2025-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_profile_is_analista_exterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_analista_exterior',
            field=models.BooleanField(default=False, verbose_name='Es Analista Exterior CDCE'),
        ),
    ]
