# Generated by Django 4.2.20 on 2025-08-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_profile_is_analista_exterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cedula_identidad',
            field=models.CharField(blank=True, help_text='Número de Cédula de Identidad', max_length=20, null=True, unique=True),
        ),
    ]
