# Generated by Django 4.2.20 on 2025-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_profile_cedula_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='apellido_becario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cedula_becario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion_residencial_becario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Residencial del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='edad_becario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_nacimiento_becario',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nacionalidad_becario',
            field=models.CharField(blank=True, choices=[('V', 'Venezolano'), ('E', 'Extranjero')], max_length=1, null=True, verbose_name='Nacionalidad del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_becario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Becario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono_becario',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del Becario'),
        ),
    ]
