# Generated by Django 4.2.20 on 2025-10-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_solicitud_apellido_becario_solicitud_cedula_becario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
